/**
 * Developer-preview toolbar contract — the ONE module shared between the
 * sandbox-only server functions (`src/server/preview.ts`) and the toolbar
 * UI (`src/components/preview/*`).
 *
 * Sandbox preview state. Everything here is pure
 * data + pure functions: no SDK, no env, no cookies — so the gating logic,
 * the persona projection, and the feature-flag whitelist are unit-testable
 * without the server runtime, and the whitelist lives in exactly one place
 * by the sandbox settings endpoint.
 *
 * SAFETY NOTE: the persona roster endpoint returns `email` and a shared
 * `password`. Neither must ever reach the browser — the switch seam is keyed
 * by persona **id** and the server resolves credentials.
 * `projectPersona` is the boundary that strips them.
 */

/**
 * Why a context may (or may not) complete a persona switch. Carried on the
 * capability so a FUTURE builder-preview context — where the board reads
 * `sandbox: true` but `auth.login` is a 403'd write inside the embedded
 * preview — can answer `canPreview: false` with `'switch-blocked'` WITHOUT
 * changing this seam.
 */
export type PreviewReason = 'sandbox' | 'not-sandbox' | 'switch-blocked';

export interface PreviewCapability {
  /** May this context COMPLETE a persona switch for this board? */
  canPreview: boolean;
  reason: PreviewReason;
}

/** A seeded scenario persona, projected safe for the browser (no credentials). */
export interface PreviewPersona {
  /** The switch key — server resolves id → email + password. */
  id: string;
  role: 'candidate' | 'employer';
  displayName: string;
  /** Secondary text: what state this persona demonstrates. */
  description: string;
  /** Machine-readable state tags (e.g. `['empty-profile']`). */
  states: string[];
}

/** The raw roster row as the sandbox endpoint returns it (server-side only). */
export interface RawPreviewPersona extends PreviewPersona {
  email: string;
}

/** Roster envelope from `GET …/sandbox/personas`. */
export interface PreviewRoster {
  personas: RawPreviewPersona[];
  /** The one published sandbox password shared by every persona. */
  password: string;
}

/** Resolve the current safe roster id while raw email stays server-side. */
export function activePersonaIdForViewer(
  personas: readonly RawPreviewPersona[],
  viewerEmail: string | null,
): string | null {
  const normalizedViewerEmail = viewerEmail?.trim().toLowerCase() ?? null;
  if (!normalizedViewerEmail) return null;
  return (
    personas.find(
      (persona) => persona.email.trim().toLowerCase() === normalizedViewerEmail,
    )?.id ?? null
  );
}

/** What the toolbar loads: capability + the browser-safe roster. */
export interface PreviewState {
  capability: PreviewCapability;
  personas: PreviewPersona[];
  /**
   * Stable, browser-safe roster identity for the signed-in preview viewer.
   * Resolved by matching email only on the server; credentials never cross
   * the projection boundary.
   */
  activePersonaId: string | null;
  /**
   * Dual-source: builder injected `CAVUNO_DEMO_BOARD`. When true the toolbar
   * shows the "Your board (real data)" entry and capability is resolved from
   * the demo tenant. When false, legacy single-key sandbox-on-primary.
   */
  demoConfigured: boolean;
  /**
   * Dual-source: `CAVUNO_DEMO_BOARD_PRIVATE=1`. When false on a dual-source
   * deploy, board-settings toggles + reseed stay hidden (shared fixture).
   */
  demoBoardPrivate: boolean;
  /** Effective data source for this request (`board` when demo is not configured). */
  dataSource: 'board' | 'demo';
}

/**
 * A captured outbound sandbox email — the letter_opener-style "Emails" panel
 * renders these newest-first. `html` is platform-generated by the board's own
 * send path and pre-sanitized (AGENTS.md hard rule 4), so the viewer renders
 * it as-is inside the rich-text container; `text` is the plain-text fallback.
 * Nothing here is a credential, but a magic-link / verification / alert-manage
 * URL rides inside the body — the whole point of the panel.
 */
export interface PreviewEmail {
  id: string;
  /** Recipient address. */
  to: string;
  subject: string;
  /** Pre-sanitized platform HTML body — rendered as-is. */
  html: string;
  /**
   * Plain-text body — the fallback when `html` is empty. Nullable on the wire:
   * many captures carry only an HTML body.
   */
  text: string | null;
  /**
   * Template/category tag, e.g. `magic_link`, `verification`, `digest`.
   * Nullable on the wire: most captures have no `emailType`, so the viewer
   * hides the tag when it is absent.
   */
  type: string | null;
  /** Capture time as epoch milliseconds (Unix ms), newest-first in the roster. */
  createdAt: number;
}

/** Envelope from `GET …/sandbox/emails` — newest-first. */
export interface PreviewEmailsRoster {
  emails: PreviewEmail[];
}

// ── Captured-email link rewriting (dev viewer only) ─────────────────────────

/**
 * The two origins the viewer's link rewrite diffs. Captured sandbox emails are
 * templated with the BOARD's canonical origin (`boardOrigin`, e.g.
 * `https://sandbox.cavuno.com` — the `seo().canonicalBase` origin), so a link
 * clicked in the viewer would leave a developer's local app for the hosted
 * board. `appOrigin` is the frontend actually serving the viewer (the request
 * origin, e.g. `http://[::1]:3030`). Both are normalized origins
 * (`new URL(x).origin`) so the comparison is protocol + host + port exact.
 */
export interface PreviewEmailOrigins {
  /** The board's canonical origin — links pointing here get rewritten. */
  boardOrigin: string;
  /** The frontend serving the viewer — links get rewritten to here. */
  appOrigin: string;
}

/**
 * Normalize any absolute URL to its origin (protocol + host + port), or `null`
 * when it is not a parseable absolute URL. The one place both the board origin
 * (from `seo().canonicalBase`) and the app origin (from the request URL) are
 * derived, so the diff compares like against like.
 */
export function toOrigin(url: string): string | null {
  try {
    return new URL(url).origin;
  } catch {
    return null;
  }
}

/** Escape a string for use as a literal inside a `RegExp`. */
function escapeRegExp(literal: string): string {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Swap the ORIGIN of a single absolute URL from `boardOrigin` to `appOrigin`,
 * preserving path + query + hash byte-for-byte from the original string
 * (entities like `&amp;` and any percent-encoding are never re-serialized —
 * only the origin prefix is replaced). Anything that is not a board-origin
 * absolute URL — a relative href, a `mailto:`, an external `https://…` — is
 * returned unchanged.
 */
function rewriteUrlOrigin(
  value: string,
  { boardOrigin, appOrigin }: PreviewEmailOrigins,
): string {
  if (boardOrigin === appOrigin) return value;
  if (toOrigin(value) !== boardOrigin) return value;
  // Locate where the path/query/hash starts in the ORIGINAL string so the
  // remainder is preserved exactly (independent of any case-normalization the
  // URL parser applied to the authority).
  const schemeSep = value.indexOf('://');
  if (schemeSep === -1) return value;
  const afterAuthority = value.slice(schemeSep + 3);
  const pathStart = afterAuthority.search(/[/?#]/);
  const remainder = pathStart === -1 ? '' : afterAuthority.slice(pathStart);
  return appOrigin + remainder;
}

/**
 * Rewrite every `href="…"` / `href='…'` in a captured email's HTML body whose
 * origin is the board's canonical origin so it opens in the frontend serving
 * the viewer instead of the hosted board. A conservative transform of the
 * platform's already-sanitized HTML (AGENTS.md rule 4): it matches only the
 * quoted value of `href` attributes and rewrites ONLY the origin — no other
 * string is interpolated. Rewritten/same-app links are also targeted at the
 * top-level app for the captured-email viewer; external links, relative links,
 * and `mailto:` links are left untouched.
 */
export function rewriteEmailHtmlLinks(
  html: string,
  origins: PreviewEmailOrigins,
): string {
  return html.replace(/<a\b[^>]*>/gi, (anchor) => {
    const href = anchor.match(/(\bhref\s*=\s*)(["'])(.*?)\2/i);
    if (!href) return anchor;

    const [attribute, prefix, quote, url] = href;
    if (!attribute || !prefix || !quote || url == null) return anchor;
    const rewritten = rewriteUrlOrigin(url, origins);
    if (toOrigin(rewritten) !== origins.appOrigin) return anchor;

    // Completion links must leave the opaque email frame and open in the
    // local/top-level app. Replace any platform-supplied target so there is a
    // single unambiguous destination; scripts and same-origin access remain
    // disabled by the iframe's sandbox.
    const withoutTarget = anchor.replace(
      /\s+target\s*=\s*(?:["'][^"']*["']|[^\s>]+)/gi,
      '',
    );
    const withHref = withoutTarget.replace(
      attribute,
      `${prefix}${quote}${rewritten}${quote}`,
    );
    return withHref.replace(/>$/, ' target="_top">');
  });
}

/**
 * Rewrite board-origin URLs in a captured email's plain-text body to the app
 * origin, guarded so only the exact origin at a URL boundary is swapped (a
 * longer look-alike host like `…cavuno.com.evil.test` is never matched). Path +
 * query + hash are preserved verbatim.
 */
export function rewriteEmailTextLinks(
  text: string,
  { boardOrigin, appOrigin }: PreviewEmailOrigins,
): string {
  if (boardOrigin === appOrigin) return text;
  const boundary = new RegExp(
    `${escapeRegExp(boardOrigin)}(?=[/?#"'\\s]|$)`,
    'g',
  );
  return text.replace(boundary, appOrigin);
}

/**
 * Rewrite the board-origin links in one captured email (HTML body + plain-text
 * fallback) to the viewer's own origin, leaving everything else — subject,
 * recipient, external links — untouched. Pure so the server fn's per-email map
 * is unit-testable without the runtime. When the origins already match, the
 * top-level navigation target is still applied to same-app links.
 */
export function rewritePreviewEmailLinks(
  email: PreviewEmail,
  origins: PreviewEmailOrigins,
): PreviewEmail {
  return {
    ...email,
    html: rewriteEmailHtmlLinks(email.html, origins),
    text:
      email.text == null
        ? email.text
        : rewriteEmailTextLinks(email.text, origins),
  };
}

/** Default page size the panel requests (matches the platform contract). */
export const PREVIEW_EMAILS_DEFAULT_LIMIT = 50;
/** Hard cap the server enforces before proxying to the sandbox endpoint. */
export const PREVIEW_EMAILS_MAX_LIMIT = 200;

/**
 * Normalize an incoming `limit` to `[1, 200]`, defaulting to 50. Pure so the
 * server fn's clamp is unit-testable without the runtime (one place
 * for the bound).
 */
export function clampEmailLimit(limit?: number): number {
  if (limit == null || !Number.isFinite(limit)) {
    return PREVIEW_EMAILS_DEFAULT_LIMIT;
  }
  return Math.min(Math.max(1, Math.floor(limit)), PREVIEW_EMAILS_MAX_LIMIT);
}

/** The viewer identity a completed switch resolves to. */
export interface PreviewViewer {
  displayName: string | null;
  email: string;
  role: 'candidate' | 'employer';
}

/** Discriminated result of a persona switch (survives the server-fn RPC boundary). */
export type PreviewSwitchResult =
  | { ok: true; viewer: PreviewViewer }
  | {
      ok: false;
      code: 'persona-unavailable' | 'not-sandbox' | 'unknown';
      message: string;
    };

/** Result of a config toggle / reseed. */
export type PreviewActionResult =
  | { ok: true }
  | {
      ok: false;
      code: 'not-sandbox' | 'not-private' | 'unknown';
      message: string;
    };

/**
 * Server-side private-shadow gate for config PATCH + reseed (F1).
 * When a dual-source deploy points at a shared public demo fixture
 * (`CAVUNO_DEMO_BOARD` set, `CAVUNO_DEMO_BOARD_PRIVATE` unset), mutating
 * endpoints must reject even if `canPreview` is true — the UI already hides
 * the controls, but a crafted server-fn RPC must not reseed / flag-toggle
 * the shared tenant. Returns `null` when the mutation is allowed (legacy
 * sandbox-on-primary, or a private demo shadow).
 */
export function rejectSharedDemoMutation(opts: {
  demoConfigured: boolean;
  demoBoardPrivate: boolean;
}): Extract<PreviewActionResult, { ok: false }> | null {
  if (opts.demoConfigured && !opts.demoBoardPrivate) {
    return {
      ok: false,
      code: 'not-private',
      message:
        'Board settings and reseed are only available on a private demo board.',
    };
  }
  return null;
}

/**
 * Talent-directory access mode. Mirrors the board config's tri-state
 * `talentDirectoryVisibility` — the sandbox config PATCH takes it verbatim.
 */
export type TalentDirectoryVisibility = 'off' | 'public' | 'employers_only';

/**
 * How the operator charges employers for the candidate directory. There is
 * deliberately no `off` member: the paywall is inert when the board sells no
 * talent plan, which is a plans decision rather than a config flag.
 */
export type TalentAccessModel = 'paid_messaging' | 'paid_unlocks_and_messaging';

export const TALENT_ACCESS_MODELS = [
  'paid_messaging',
  'paid_unlocks_and_messaging',
] as const satisfies readonly TalentAccessModel[];

export const TALENT_DIRECTORY_VISIBILITIES = [
  'off',
  'public',
  'employers_only',
] as const satisfies readonly TalentDirectoryVisibility[];

/**
 * A whitelisted, sandbox-toggleable board-CONFIG key — the toolbar's "Board
 * settings" section renders one control per entry, and the server validates
 * incoming PATCH keys against `SANDBOX_CONFIG_WHITELIST`.
 *
 * The `key` is the exact board-config key `PATCH /sandbox/config` accepts (the
 * platform vocabulary), NOT a public `features`-map name — the two do not
 * overlap, which is why the previous public-name payloads 400'd. `kind` drives
 * the control: `'boolean'` → a Switch (value maps to `true`/`false`);
 * `'enum'` → a small tri-state select (value maps directly to the enum member).
 *
 * Current values are read from the PUBLIC board context via
 * `toPreviewBoardConfig` — the one place that bridges the public read shape
 * onto these write keys. Reserved keys (`sandboxBoard`, `isTestBoard`,
 * `passwordProtectionEnabled`, …) are deliberately absent.
 */
export interface PreviewBooleanFlag {
  /**
   * Parent flags this capability depends on (all must be ON for the control
   * to be interactive) — mirrors the dashboard's dependency gating: ATS needs
   * employer accounts; messaging needs employers AND candidates. The stored
   * value is never mutated by gating; the switch just disables.
   */
  requires?: readonly ('candidatesEnabled' | 'employersEnabled')[];
  /** Short hint rendered when `requires` is unmet. */
  requiresNote?: string;
  key:
    | 'jobAccessPaywallEnabled'
    | 'blogEnabled'
    | 'jobAlertsEnabled'
    | 'jobRecommendationsEnabled'
    | 'candidatesEnabled'
    | 'employersEnabled'
    | 'nativeApplicationsEnabled'
    | 'applicantMessagingEnabled'
    | 'registrationWallEnabled';
  kind: 'boolean';
  label: string;
  description: string;
}

/**
 * An enum-valued flag. Discriminated by `key` so each control keeps its own
 * option union — a `talentAccessModel` select can never be handed a
 * directory-visibility member.
 */
export type PreviewEnumFlag =
  | {
      key: 'talentDirectoryVisibility';
      kind: 'enum';
      label: string;
      description: string;
      /** The enum members, in display order; labels come from the message catalog. */
      options: readonly TalentDirectoryVisibility[];
    }
  | {
      key: 'talentAccessModel';
      kind: 'enum';
      label: string;
      description: string;
      options: readonly TalentAccessModel[];
    };

export type PreviewFeatureFlag = PreviewBooleanFlag | PreviewEnumFlag;

// Move them into the toolbar layer (or Paraglide keys) when preview i18n is
// prioritized — leave English here for now.
export const PREVIEW_FEATURE_FLAGS: readonly PreviewFeatureFlag[] = [
  {
    key: 'jobAccessPaywallEnabled',
    kind: 'boolean',
    label: 'Candidate paywall',
    description:
      'Gate job browsing behind a paid offer (anonymous gatedCount).',
  },
  {
    key: 'talentDirectoryVisibility',
    kind: 'enum',
    label: 'Talent directory',
    description: 'Who can see the /talent candidate directory.',
    options: TALENT_DIRECTORY_VISIBILITIES,
  },
  {
    key: 'talentAccessModel',
    kind: 'enum',
    label: 'Talent access model',
    description:
      'How employers pay for the directory: messaging only, or unlocks as well.',
    options: TALENT_ACCESS_MODELS,
  },
  {
    key: 'blogEnabled',
    kind: 'boolean',
    label: 'Blog',
    description: 'Enable the board blog surfaces.',
  },
  {
    key: 'jobAlertsEnabled',
    kind: 'boolean',
    label: 'Job alerts',
    description: 'Allow anonymous job-alert subscriptions.',
  },
  {
    key: 'jobRecommendationsEnabled',
    kind: 'boolean',
    label: 'Job recommendations',
    description:
      'Show signed-in candidates personalized job matches based on their profile and resume.',
    requires: ['candidatesEnabled'],
    requiresNote: 'Requires candidate accounts.',
  },
  {
    key: 'candidatesEnabled',
    kind: 'boolean',
    label: 'Candidate accounts',
    description: 'Enable candidate profiles and sign-up.',
  },
  {
    key: 'employersEnabled',
    kind: 'boolean',
    label: 'Employer self-serve',
    description: 'Enable employer sign-up and self-serve flows.',
  },
  {
    key: 'nativeApplicationsEnabled',
    kind: 'boolean',
    label: 'Native applications',
    // Off = external-applications-only board: native apply 422s
    // (applications_native_disabled) and the built-in apply flow hides.
    description: 'Built-in ATS apply — off means external-applications-only.',
    requires: ['employersEnabled'],
    requiresNote: 'Requires employer self-serve.',
  },
  {
    key: 'applicantMessagingEnabled',
    kind: 'boolean',
    label: 'Applicant messaging',
    // Off = the whole surface family is absent: inbox, dock, message CTAs;
    // the conversations API rejects with messaging_disabled.
    description: 'Applicant–employer messaging surfaces and sends.',
    requires: ['employersEnabled', 'candidatesEnabled'],
    requiresNote: 'Requires employer self-serve and candidate accounts.',
  },
  {
    key: 'registrationWallEnabled',
    kind: 'boolean',
    label: 'Registration wall',
    // Gates APPLYING, not browsing: the platform 403s guest applications
    // (applications_guest_not_allowed) when enabled; jobs stay visible.
    description: 'Require sign-in to apply — disables guest applications.',
  },
] as const;

/**
 * The board-config keys `PATCH /sandbox/config` accepts. Mirrors the platform
 * whitelist in `convex/boards/sandboxPersonaManifest.ts` (the source of truth) —
 * keep in sync. `jobAccessPreviewCount` is accepted by the API but has no UI
 * control (see `PREVIEW_FEATURE_FLAGS`); it stays on this whitelist so the
 * frontend's defense-in-depth filter matches the platform exactly.
 */
export const SANDBOX_CONFIG_WHITELIST: ReadonlySet<string> = new Set([
  'jobAccessPaywallEnabled',
  'jobAccessPreviewCount',
  'talentDirectoryVisibility',
  'talentAccessModel',
  'blogEnabled',
  'jobAlertsEnabled',
  'jobRecommendationsEnabled',
  'candidatesEnabled',
  'employersEnabled',
  'nativeApplicationsEnabled',
  'applicantMessagingEnabled',
  'registrationWallEnabled',
]);

/**
 * Current values of the sandbox-toggleable config keys, projected from the
 * PUBLIC board context. The read side speaks the public `features` map plus the
 * top-level `talentDirectoryVisibility`; the write side (`PATCH /sandbox/config`)
 * speaks board-config keys — this is the single bridge between them.
 */
export interface PreviewBoardConfig {
  jobAccessPaywallEnabled: boolean;
  talentDirectoryVisibility: TalentDirectoryVisibility;
  talentAccessModel: TalentAccessModel;
  blogEnabled: boolean;
  jobAlertsEnabled: boolean;
  jobRecommendationsEnabled: boolean;
  candidatesEnabled: boolean;
  employersEnabled: boolean;
  nativeApplicationsEnabled: boolean;
  applicantMessagingEnabled: boolean;
  registrationWallEnabled: boolean;
}

export type SandboxConfigValue = string | number | boolean | null;
export type SandboxConfigKey =
  | keyof PreviewBoardConfig
  | 'jobAccessPreviewCount';
export interface SandboxConfigPatch {
  jobAccessPaywallEnabled?: SandboxConfigValue;
  jobAccessPreviewCount?: SandboxConfigValue;
  talentDirectoryVisibility?: SandboxConfigValue;
  talentAccessModel?: SandboxConfigValue;
  blogEnabled?: SandboxConfigValue;
  jobAlertsEnabled?: SandboxConfigValue;
  jobRecommendationsEnabled?: SandboxConfigValue;
  candidatesEnabled?: SandboxConfigValue;
  employersEnabled?: SandboxConfigValue;
  nativeApplicationsEnabled?: SandboxConfigValue;
  applicantMessagingEnabled?: SandboxConfigValue;
  registrationWallEnabled?: SandboxConfigValue;
}

function isSandboxConfigKey(key: string): key is SandboxConfigKey {
  return SANDBOX_CONFIG_WHITELIST.has(key);
}

export function toPreviewBoardConfig(context: {
  features: {
    candidatePaywall: boolean;
    blog: boolean;
    jobAlerts: boolean;
    jobRecommendationsEnabled?: boolean;
    candidates: boolean;
    employers: boolean;
    registrationWall: boolean;
    talentDirectory?: 'off' | 'public' | 'employers_only';
    /**
     * Runtime flags `@cavuno/board@1.38.0` does not type yet (see
     * `src/board/board-feature-flags.ts`) — optional here, absent ⇒ ON.
     */
    nativeApplications?: boolean;
    messaging?: boolean;
  };
  /** Nullable off an API deployment predating the tri-state slice — defaults to `'off'`. */
  talentDirectoryVisibility: TalentDirectoryVisibility | null;
  /**
   * `null` when the operator has not chosen a model explicitly. The board API
   * documents the fallback as inference from the published talent plans; the
   * toolbar has no plan list, so it shows the unlocks model, which is what a
   * board selling unlocks infers to and what the sandbox baseline sets.
   */
  talentAccessModel?: TalentAccessModel | null;
}): PreviewBoardConfig {
  return {
    jobAccessPaywallEnabled: context.features.candidatePaywall,
    talentAccessModel:
      context.talentAccessModel ?? 'paid_unlocks_and_messaging',
    talentDirectoryVisibility:
      // 4.0.0: enum lives on features.talentDirectory ('off' is truthy!).
      context.features.talentDirectory ??
      context.talentDirectoryVisibility ??
      'off',
    blogEnabled: context.features.blog,
    jobAlertsEnabled: context.features.jobAlerts,
    jobRecommendationsEnabled:
      context.features.jobRecommendationsEnabled ?? true,
    candidatesEnabled: context.features.candidates,
    employersEnabled: context.features.employers,
    nativeApplicationsEnabled: context.features.nativeApplications ?? true,
    applicantMessagingEnabled: context.features.messaging ?? true,
    registrationWallEnabled: context.features.registrationWall,
  };
}

/**
 * v0 capability logic: capable iff the board is a sandbox.
 *
 * Callers pass `sandbox: true` when the sandbox surface is reachable
 * (`GET /sandbox/personas` succeeds). Public board context no longer
 * carries a `sandbox` flag (SDK 2.0+). The reason field keeps the seam
 * future-proof (see `PreviewReason`).
 */
export function resolveCapability(context: {
  sandbox: boolean;
}): PreviewCapability {
  if (context.sandbox) return { canPreview: true, reason: 'sandbox' };
  return { canPreview: false, reason: 'not-sandbox' };
}

/** Strip credentials from a roster row before it crosses to the browser. */
export function projectPersona(raw: RawPreviewPersona): PreviewPersona {
  return {
    id: raw.id,
    role: raw.role,
    displayName: raw.displayName,
    description: raw.description,
    states: raw.states,
  };
}

/**
 * The unmet parents of a boolean flag under the current config — empty when
 * the flag has no dependencies or all are ON. Pure, so the toolbar's gating
 * is unit-testable without rendering.
 */
export function unmetFlagRequirements(
  flag: PreviewFeatureFlag,
  config: PreviewBoardConfig,
): readonly ('candidatesEnabled' | 'employersEnabled')[] {
  if (flag.kind !== 'boolean' || !flag.requires) return [];
  return flag.requires.filter((parent) => config[parent] !== true);
}

/**
 * Defense in depth: drop any key the caller sent that is not on
 * `SANDBOX_CONFIG_WHITELIST` BEFORE it reaches the config endpoint. The API
 * whitelists too, but the frontend must never forward an arbitrary config bag.
 */
export function pickWhitelistedConfig(
  config: SandboxConfigPatch,
): SandboxConfigPatch {
  const out: SandboxConfigPatch = {};
  for (const [key, value] of Object.entries(config)) {
    if (isSandboxConfigKey(key)) {
      out[key] = value;
    }
  }
  return out;
}

type PreviewPersonaGroups = {
  candidate: PreviewPersona[];
  employer: PreviewPersona[];
};

/** Group personas by role for the toolbar's sectioned menu. */
export function groupPersonasByRole(
  personas: readonly PreviewPersona[],
): PreviewPersonaGroups {
  return {
    candidate: personas.filter((p) => p.role === 'candidate'),
    employer: personas.filter((p) => p.role === 'employer'),
  };
}
