/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PostRouteImport } from './routes/post'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as IndexnowKeyDottxtRouteImport } from './routes/indexnow-key[.]txt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as SalariesIndexRouteImport } from './routes/salaries.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as EmployersIndexRouteImport } from './routes/employers.index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SitemapFileRouteImport } from './routes/sitemap.$file'
import { Route as PHandleRouteImport } from './routes/p.$handle'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as MeApplicationsRouteImport } from './routes/me.applications'
import { Route as MeAlertsRouteImport } from './routes/me.alerts'
import { Route as JobsRssDotxmlRouteImport } from './routes/jobs.rss[.]xml'
import { Route as JobsKeywordRouteImport } from './routes/jobs.$keyword'
import { Route as GoSplatRouteImport } from './routes/go.$'
import { Route as EmployersDashboardRouteImport } from './routes/employers.dashboard'
import { Route as EmbedJobsRouteImport } from './routes/embed.jobs'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as BlogPostSlugRouteImport } from './routes/blog.$postSlug'
import { Route as AuthVerifyWorkEmailRouteImport } from './routes/auth.verify-work-email'
import { Route as AuthVerifyEmailRequiredRouteImport } from './routes/auth.verify-email-required'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthOauthCompleteRouteImport } from './routes/auth.oauth-complete'
import { Route as AuthMagicLinkRouteImport } from './routes/auth.magic-link'
import { Route as AuthJoinRouteImport } from './routes/auth.join'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthConfirmEmailChangeRouteImport } from './routes/auth.confirm-email-change'
import { Route as AlertsManageRouteImport } from './routes/alerts.manage'
import { Route as AlertsConfirmRouteImport } from './routes/alerts.confirm'
import { Route as AccountAccessRouteImport } from './routes/account_.access'
import { Route as DotwellKnownCavunoDotjsonRouteImport } from './routes/[.]well-known.cavuno[.]json'
import { Route as SalariesTitlesIndexRouteImport } from './routes/salaries.titles.index'
import { Route as SalariesSkillsIndexRouteImport } from './routes/salaries.skills.index'
import { Route as SalariesLocationsIndexRouteImport } from './routes/salaries.locations.index'
import { Route as SalariesCompaniesIndexRouteImport } from './routes/salaries.companies.index'
import { Route as JobsLocationsIndexRouteImport } from './routes/jobs.locations.index'
import { Route as CompaniesCompanySlugIndexRouteImport } from './routes/companies.$companySlug.index'
import { Route as JobsSkillsSkillRouteImport } from './routes/jobs.skills.$skill'
import { Route as EmployersOnboardingSlugRouteImport } from './routes/employers.onboarding.$slug'
import { Route as EmployersInvitesAcceptRouteImport } from './routes/employers.invites.accept'
import { Route as CompaniesMarketsMarketRouteImport } from './routes/companies.markets.$market'
import { Route as BlogTagTagSlugRouteImport } from './routes/blog.tag.$tagSlug'
import { Route as BlogOgChar123postSlugChar125DotjsonRouteImport } from './routes/blog.og.{$postSlug}[.]json'
import { Route as BlogAuthorAuthorSlugRouteImport } from './routes/blog.author.$authorSlug'
import { Route as BlogPostSlugOgRouteImport } from './routes/blog.$postSlug.og'
import { Route as AuthEmployerSignUpRouteImport } from './routes/auth.employer.sign-up'
import { Route as SalariesTitlesSlugIndexRouteImport } from './routes/salaries.titles.$slug.index'
import { Route as SalariesSkillsSlugIndexRouteImport } from './routes/salaries.skills.$slug.index'
import { Route as SalariesLocationsSlugIndexRouteImport } from './routes/salaries.locations.$slug.index'
import { Route as JobsLocationsLocationIndexRouteImport } from './routes/jobs.locations.$location.index'
import { Route as EmployersCompaniesSlugIndexRouteImport } from './routes/employers.companies.$slug.index'
import { Route as CompaniesCompanySlugSalariesIndexRouteImport } from './routes/companies.$companySlug.salaries.index'
import { Route as CompaniesCompanySlugJobsIndexRouteImport } from './routes/companies.$companySlug.jobs.index'
import { Route as SalariesTitlesSlugLocationsRouteImport } from './routes/salaries.titles.$slug.locations'
import { Route as SalariesTitlesSlugLocationSlugRouteImport } from './routes/salaries.titles.$slug.$locationSlug'
import { Route as SalariesSkillsSlugLocationsRouteImport } from './routes/salaries.skills.$slug.locations'
import { Route as SalariesSkillsSlugLocationSlugRouteImport } from './routes/salaries.skills.$slug.$locationSlug'
import { Route as SalariesLocationsSlugTitlesRouteImport } from './routes/salaries.locations.$slug.titles'
import { Route as SalariesLocationsSlugSkillsRouteImport } from './routes/salaries.locations.$slug.skills'
import { Route as JobsLocationsLocationKeywordRouteImport } from './routes/jobs.locations.$location.$keyword'
import { Route as EmployersCompaniesSlugProfileRouteImport } from './routes/employers.companies.$slug.profile'
import { Route as EmployersCompaniesSlugMembersRouteImport } from './routes/employers.companies.$slug.members'
import { Route as CompaniesCompanySlugSalariesCategorySlugRouteImport } from './routes/companies.$companySlug.salaries.$categorySlug'
import { Route as CompaniesCompanySlugJobsJobSlugRouteImport } from './routes/companies.$companySlug.jobs.$jobSlug'
import { Route as JobsLocationsLocationSkillsSkillRouteImport } from './routes/jobs.locations.$location.skills.$skill'
import { Route as EmployersCompaniesSlugJobsNewRouteImport } from './routes/employers.companies.$slug.jobs.new'
import { Route as CompaniesCompanySlugJobsJobSlugOgRouteImport } from './routes/companies.$companySlug.jobs.$jobSlug.og'
import { Route as EmployersCompaniesSlugJobsJobIdEditRouteImport } from './routes/employers.companies.$slug.jobs.$jobId.edit'
import { Route as EmployersCompaniesSlugJobsJobIdApplicantsRouteImport } from './routes/employers.companies.$slug.jobs.$jobId.applicants'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexnowKeyDottxtRoute = IndexnowKeyDottxtRouteImport.update({
  id: '/indexnow-key.txt',
  path: '/indexnow-key.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesIndexRoute = SalariesIndexRouteImport.update({
  id: '/salaries/',
  path: '/salaries/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersIndexRoute = EmployersIndexRouteImport.update({
  id: '/employers/',
  path: '/employers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapFileRoute = SitemapFileRouteImport.update({
  id: '/sitemap/$file',
  path: '/sitemap/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => MessagesRoute,
} as any)
const MeApplicationsRoute = MeApplicationsRouteImport.update({
  id: '/me/applications',
  path: '/me/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MeAlertsRoute = MeAlertsRouteImport.update({
  id: '/me/alerts',
  path: '/me/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRssDotxmlRoute = JobsRssDotxmlRouteImport.update({
  id: '/jobs/rss.xml',
  path: '/jobs/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsKeywordRoute = JobsKeywordRouteImport.update({
  id: '/jobs/$keyword',
  path: '/jobs/$keyword',
  getParentRoute: () => rootRouteImport,
} as any)
const GoSplatRoute = GoSplatRouteImport.update({
  id: '/go/$',
  path: '/go/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersDashboardRoute = EmployersDashboardRouteImport.update({
  id: '/employers/dashboard',
  path: '/employers/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedJobsRoute = EmbedJobsRouteImport.update({
  id: '/embed/jobs',
  path: '/embed/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostSlugRoute = BlogPostSlugRouteImport.update({
  id: '/blog/$postSlug',
  path: '/blog/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyWorkEmailRoute = AuthVerifyWorkEmailRouteImport.update({
  id: '/auth/verify-work-email',
  path: '/auth/verify-work-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRequiredRoute = AuthVerifyEmailRequiredRouteImport.update({
  id: '/auth/verify-email-required',
  path: '/auth/verify-email-required',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOauthCompleteRoute = AuthOauthCompleteRouteImport.update({
  id: '/auth/oauth-complete',
  path: '/auth/oauth-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/auth/magic-link',
  path: '/auth/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJoinRoute = AuthJoinRouteImport.update({
  id: '/auth/join',
  path: '/auth/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmEmailChangeRoute = AuthConfirmEmailChangeRouteImport.update({
  id: '/auth/confirm-email-change',
  path: '/auth/confirm-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsManageRoute = AlertsManageRouteImport.update({
  id: '/alerts/manage',
  path: '/alerts/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsConfirmRoute = AlertsConfirmRouteImport.update({
  id: '/alerts/confirm',
  path: '/alerts/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccessRoute = AccountAccessRouteImport.update({
  id: '/account_/access',
  path: '/account/access',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownCavunoDotjsonRoute =
  DotwellKnownCavunoDotjsonRouteImport.update({
    id: '/.well-known/cavuno.json',
    path: '/.well-known/cavuno.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalariesTitlesIndexRoute = SalariesTitlesIndexRouteImport.update({
  id: '/salaries/titles/',
  path: '/salaries/titles/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesSkillsIndexRoute = SalariesSkillsIndexRouteImport.update({
  id: '/salaries/skills/',
  path: '/salaries/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesLocationsIndexRoute = SalariesLocationsIndexRouteImport.update({
  id: '/salaries/locations/',
  path: '/salaries/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesCompaniesIndexRoute = SalariesCompaniesIndexRouteImport.update({
  id: '/salaries/companies/',
  path: '/salaries/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsLocationsIndexRoute = JobsLocationsIndexRouteImport.update({
  id: '/jobs/locations/',
  path: '/jobs/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanySlugIndexRoute =
  CompaniesCompanySlugIndexRouteImport.update({
    id: '/companies/$companySlug/',
    path: '/companies/$companySlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobsSkillsSkillRoute = JobsSkillsSkillRouteImport.update({
  id: '/jobs/skills/$skill',
  path: '/jobs/skills/$skill',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersOnboardingSlugRoute = EmployersOnboardingSlugRouteImport.update({
  id: '/employers/onboarding/$slug',
  path: '/employers/onboarding/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersInvitesAcceptRoute = EmployersInvitesAcceptRouteImport.update({
  id: '/employers/invites/accept',
  path: '/employers/invites/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesMarketsMarketRoute = CompaniesMarketsMarketRouteImport.update({
  id: '/companies/markets/$market',
  path: '/companies/markets/$market',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagTagSlugRoute = BlogTagTagSlugRouteImport.update({
  id: '/blog/tag/$tagSlug',
  path: '/blog/tag/$tagSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOgChar123postSlugChar125DotjsonRoute =
  BlogOgChar123postSlugChar125DotjsonRouteImport.update({
    id: '/blog/og/{$postSlug}.json',
    path: '/blog/og/{$postSlug}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAuthorAuthorSlugRoute = BlogAuthorAuthorSlugRouteImport.update({
  id: '/blog/author/$authorSlug',
  path: '/blog/author/$authorSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPostSlugOgRoute = BlogPostSlugOgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => BlogPostSlugRoute,
} as any)
const AuthEmployerSignUpRoute = AuthEmployerSignUpRouteImport.update({
  id: '/auth/employer/sign-up',
  path: '/auth/employer/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesTitlesSlugIndexRoute = SalariesTitlesSlugIndexRouteImport.update({
  id: '/salaries/titles/$slug/',
  path: '/salaries/titles/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesSkillsSlugIndexRoute = SalariesSkillsSlugIndexRouteImport.update({
  id: '/salaries/skills/$slug/',
  path: '/salaries/skills/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalariesLocationsSlugIndexRoute =
  SalariesLocationsSlugIndexRouteImport.update({
    id: '/salaries/locations/$slug/',
    path: '/salaries/locations/$slug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobsLocationsLocationIndexRoute =
  JobsLocationsLocationIndexRouteImport.update({
    id: '/jobs/locations/$location/',
    path: '/jobs/locations/$location/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployersCompaniesSlugIndexRoute =
  EmployersCompaniesSlugIndexRouteImport.update({
    id: '/employers/companies/$slug/',
    path: '/employers/companies/$slug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanySlugSalariesIndexRoute =
  CompaniesCompanySlugSalariesIndexRouteImport.update({
    id: '/companies/$companySlug/salaries/',
    path: '/companies/$companySlug/salaries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanySlugJobsIndexRoute =
  CompaniesCompanySlugJobsIndexRouteImport.update({
    id: '/companies/$companySlug/jobs/',
    path: '/companies/$companySlug/jobs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalariesTitlesSlugLocationsRoute =
  SalariesTitlesSlugLocationsRouteImport.update({
    id: '/salaries/titles/$slug/locations',
    path: '/salaries/titles/$slug/locations',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalariesTitlesSlugLocationSlugRoute =
  SalariesTitlesSlugLocationSlugRouteImport.update({
    id: '/salaries/titles/$slug/$locationSlug',
    path: '/salaries/titles/$slug/$locationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalariesSkillsSlugLocationsRoute =
  SalariesSkillsSlugLocationsRouteImport.update({
    id: '/salaries/skills/$slug/locations',
    path: '/salaries/skills/$slug/locations',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalariesSkillsSlugLocationSlugRoute =
  SalariesSkillsSlugLocationSlugRouteImport.update({
    id: '/salaries/skills/$slug/$locationSlug',
    path: '/salaries/skills/$slug/$locationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalariesLocationsSlugTitlesRoute =
  SalariesLocationsSlugTitlesRouteImport.update({
    id: '/salaries/locations/$slug/titles',
    path: '/salaries/locations/$slug/titles',
    getParentRoute: () => rootRouteImport,
  } as any)
const SalariesLocationsSlugSkillsRoute =
  SalariesLocationsSlugSkillsRouteImport.update({
    id: '/salaries/locations/$slug/skills',
    path: '/salaries/locations/$slug/skills',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobsLocationsLocationKeywordRoute =
  JobsLocationsLocationKeywordRouteImport.update({
    id: '/jobs/locations/$location/$keyword',
    path: '/jobs/locations/$location/$keyword',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployersCompaniesSlugProfileRoute =
  EmployersCompaniesSlugProfileRouteImport.update({
    id: '/employers/companies/$slug/profile',
    path: '/employers/companies/$slug/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployersCompaniesSlugMembersRoute =
  EmployersCompaniesSlugMembersRouteImport.update({
    id: '/employers/companies/$slug/members',
    path: '/employers/companies/$slug/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanySlugSalariesCategorySlugRoute =
  CompaniesCompanySlugSalariesCategorySlugRouteImport.update({
    id: '/companies/$companySlug/salaries/$categorySlug',
    path: '/companies/$companySlug/salaries/$categorySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanySlugJobsJobSlugRoute =
  CompaniesCompanySlugJobsJobSlugRouteImport.update({
    id: '/companies/$companySlug/jobs/$jobSlug',
    path: '/companies/$companySlug/jobs/$jobSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobsLocationsLocationSkillsSkillRoute =
  JobsLocationsLocationSkillsSkillRouteImport.update({
    id: '/jobs/locations/$location/skills/$skill',
    path: '/jobs/locations/$location/skills/$skill',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployersCompaniesSlugJobsNewRoute =
  EmployersCompaniesSlugJobsNewRouteImport.update({
    id: '/employers/companies/$slug/jobs/new',
    path: '/employers/companies/$slug/jobs/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesCompanySlugJobsJobSlugOgRoute =
  CompaniesCompanySlugJobsJobSlugOgRouteImport.update({
    id: '/og',
    path: '/og',
    getParentRoute: () => CompaniesCompanySlugJobsJobSlugRoute,
  } as any)
const EmployersCompaniesSlugJobsJobIdEditRoute =
  EmployersCompaniesSlugJobsJobIdEditRouteImport.update({
    id: '/employers/companies/$slug/jobs/$jobId/edit',
    path: '/employers/companies/$slug/jobs/$jobId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployersCompaniesSlugJobsJobIdApplicantsRoute =
  EmployersCompaniesSlugJobsJobIdApplicantsRouteImport.update({
    id: '/employers/companies/$slug/jobs/$jobId/applicants',
    path: '/employers/companies/$slug/jobs/$jobId/applicants',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/apply': typeof ApplyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/impressum': typeof ImpressumRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRouteWithChildren
  '/password': typeof PasswordRoute
  '/post': typeof PostRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/settings': typeof SettingsRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/.well-known/cavuno.json': typeof DotwellKnownCavunoDotjsonRoute
  '/account/access': typeof AccountAccessRoute
  '/alerts/confirm': typeof AlertsConfirmRoute
  '/alerts/manage': typeof AlertsManageRoute
  '/auth/confirm-email-change': typeof AuthConfirmEmailChangeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join': typeof AuthJoinRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/oauth-complete': typeof AuthOauthCompleteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-email-required': typeof AuthVerifyEmailRequiredRoute
  '/auth/verify-work-email': typeof AuthVerifyWorkEmailRoute
  '/blog/$postSlug': typeof BlogPostSlugRouteWithChildren
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/embed/jobs': typeof EmbedJobsRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
  '/go/$': typeof GoSplatRoute
  '/jobs/$keyword': typeof JobsKeywordRoute
  '/jobs/rss.xml': typeof JobsRssDotxmlRoute
  '/me/alerts': typeof MeAlertsRoute
  '/me/applications': typeof MeApplicationsRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/p/$handle': typeof PHandleRoute
  '/sitemap/$file': typeof SitemapFileRoute
  '/blog/': typeof BlogIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/salaries/': typeof SalariesIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/auth/employer/sign-up': typeof AuthEmployerSignUpRoute
  '/blog/$postSlug/og': typeof BlogPostSlugOgRoute
  '/blog/author/$authorSlug': typeof BlogAuthorAuthorSlugRoute
  '/blog/og/{$postSlug}.json': typeof BlogOgChar123postSlugChar125DotjsonRoute
  '/blog/tag/$tagSlug': typeof BlogTagTagSlugRoute
  '/companies/markets/$market': typeof CompaniesMarketsMarketRoute
  '/employers/invites/accept': typeof EmployersInvitesAcceptRoute
  '/employers/onboarding/$slug': typeof EmployersOnboardingSlugRoute
  '/jobs/skills/$skill': typeof JobsSkillsSkillRoute
  '/companies/$companySlug/': typeof CompaniesCompanySlugIndexRoute
  '/jobs/locations/': typeof JobsLocationsIndexRoute
  '/salaries/companies/': typeof SalariesCompaniesIndexRoute
  '/salaries/locations/': typeof SalariesLocationsIndexRoute
  '/salaries/skills/': typeof SalariesSkillsIndexRoute
  '/salaries/titles/': typeof SalariesTitlesIndexRoute
  '/companies/$companySlug/jobs/$jobSlug': typeof CompaniesCompanySlugJobsJobSlugRouteWithChildren
  '/companies/$companySlug/salaries/$categorySlug': typeof CompaniesCompanySlugSalariesCategorySlugRoute
  '/employers/companies/$slug/members': typeof EmployersCompaniesSlugMembersRoute
  '/employers/companies/$slug/profile': typeof EmployersCompaniesSlugProfileRoute
  '/jobs/locations/$location/$keyword': typeof JobsLocationsLocationKeywordRoute
  '/salaries/locations/$slug/skills': typeof SalariesLocationsSlugSkillsRoute
  '/salaries/locations/$slug/titles': typeof SalariesLocationsSlugTitlesRoute
  '/salaries/skills/$slug/$locationSlug': typeof SalariesSkillsSlugLocationSlugRoute
  '/salaries/skills/$slug/locations': typeof SalariesSkillsSlugLocationsRoute
  '/salaries/titles/$slug/$locationSlug': typeof SalariesTitlesSlugLocationSlugRoute
  '/salaries/titles/$slug/locations': typeof SalariesTitlesSlugLocationsRoute
  '/companies/$companySlug/jobs/': typeof CompaniesCompanySlugJobsIndexRoute
  '/companies/$companySlug/salaries/': typeof CompaniesCompanySlugSalariesIndexRoute
  '/employers/companies/$slug/': typeof EmployersCompaniesSlugIndexRoute
  '/jobs/locations/$location/': typeof JobsLocationsLocationIndexRoute
  '/salaries/locations/$slug/': typeof SalariesLocationsSlugIndexRoute
  '/salaries/skills/$slug/': typeof SalariesSkillsSlugIndexRoute
  '/salaries/titles/$slug/': typeof SalariesTitlesSlugIndexRoute
  '/companies/$companySlug/jobs/$jobSlug/og': typeof CompaniesCompanySlugJobsJobSlugOgRoute
  '/employers/companies/$slug/jobs/new': typeof EmployersCompaniesSlugJobsNewRoute
  '/jobs/locations/$location/skills/$skill': typeof JobsLocationsLocationSkillsSkillRoute
  '/employers/companies/$slug/jobs/$jobId/applicants': typeof EmployersCompaniesSlugJobsJobIdApplicantsRoute
  '/employers/companies/$slug/jobs/$jobId/edit': typeof EmployersCompaniesSlugJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/apply': typeof ApplyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/impressum': typeof ImpressumRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRouteWithChildren
  '/password': typeof PasswordRoute
  '/post': typeof PostRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/settings': typeof SettingsRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/.well-known/cavuno.json': typeof DotwellKnownCavunoDotjsonRoute
  '/account/access': typeof AccountAccessRoute
  '/alerts/confirm': typeof AlertsConfirmRoute
  '/alerts/manage': typeof AlertsManageRoute
  '/auth/confirm-email-change': typeof AuthConfirmEmailChangeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join': typeof AuthJoinRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/oauth-complete': typeof AuthOauthCompleteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-email-required': typeof AuthVerifyEmailRequiredRoute
  '/auth/verify-work-email': typeof AuthVerifyWorkEmailRoute
  '/blog/$postSlug': typeof BlogPostSlugRouteWithChildren
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/embed/jobs': typeof EmbedJobsRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
  '/go/$': typeof GoSplatRoute
  '/jobs/$keyword': typeof JobsKeywordRoute
  '/jobs/rss.xml': typeof JobsRssDotxmlRoute
  '/me/alerts': typeof MeAlertsRoute
  '/me/applications': typeof MeApplicationsRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/p/$handle': typeof PHandleRoute
  '/sitemap/$file': typeof SitemapFileRoute
  '/blog': typeof BlogIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/employers': typeof EmployersIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/salaries': typeof SalariesIndexRoute
  '/talent': typeof TalentIndexRoute
  '/auth/employer/sign-up': typeof AuthEmployerSignUpRoute
  '/blog/$postSlug/og': typeof BlogPostSlugOgRoute
  '/blog/author/$authorSlug': typeof BlogAuthorAuthorSlugRoute
  '/blog/og/{$postSlug}.json': typeof BlogOgChar123postSlugChar125DotjsonRoute
  '/blog/tag/$tagSlug': typeof BlogTagTagSlugRoute
  '/companies/markets/$market': typeof CompaniesMarketsMarketRoute
  '/employers/invites/accept': typeof EmployersInvitesAcceptRoute
  '/employers/onboarding/$slug': typeof EmployersOnboardingSlugRoute
  '/jobs/skills/$skill': typeof JobsSkillsSkillRoute
  '/companies/$companySlug': typeof CompaniesCompanySlugIndexRoute
  '/jobs/locations': typeof JobsLocationsIndexRoute
  '/salaries/companies': typeof SalariesCompaniesIndexRoute
  '/salaries/locations': typeof SalariesLocationsIndexRoute
  '/salaries/skills': typeof SalariesSkillsIndexRoute
  '/salaries/titles': typeof SalariesTitlesIndexRoute
  '/companies/$companySlug/jobs/$jobSlug': typeof CompaniesCompanySlugJobsJobSlugRouteWithChildren
  '/companies/$companySlug/salaries/$categorySlug': typeof CompaniesCompanySlugSalariesCategorySlugRoute
  '/employers/companies/$slug/members': typeof EmployersCompaniesSlugMembersRoute
  '/employers/companies/$slug/profile': typeof EmployersCompaniesSlugProfileRoute
  '/jobs/locations/$location/$keyword': typeof JobsLocationsLocationKeywordRoute
  '/salaries/locations/$slug/skills': typeof SalariesLocationsSlugSkillsRoute
  '/salaries/locations/$slug/titles': typeof SalariesLocationsSlugTitlesRoute
  '/salaries/skills/$slug/$locationSlug': typeof SalariesSkillsSlugLocationSlugRoute
  '/salaries/skills/$slug/locations': typeof SalariesSkillsSlugLocationsRoute
  '/salaries/titles/$slug/$locationSlug': typeof SalariesTitlesSlugLocationSlugRoute
  '/salaries/titles/$slug/locations': typeof SalariesTitlesSlugLocationsRoute
  '/companies/$companySlug/jobs': typeof CompaniesCompanySlugJobsIndexRoute
  '/companies/$companySlug/salaries': typeof CompaniesCompanySlugSalariesIndexRoute
  '/employers/companies/$slug': typeof EmployersCompaniesSlugIndexRoute
  '/jobs/locations/$location': typeof JobsLocationsLocationIndexRoute
  '/salaries/locations/$slug': typeof SalariesLocationsSlugIndexRoute
  '/salaries/skills/$slug': typeof SalariesSkillsSlugIndexRoute
  '/salaries/titles/$slug': typeof SalariesTitlesSlugIndexRoute
  '/companies/$companySlug/jobs/$jobSlug/og': typeof CompaniesCompanySlugJobsJobSlugOgRoute
  '/employers/companies/$slug/jobs/new': typeof EmployersCompaniesSlugJobsNewRoute
  '/jobs/locations/$location/skills/$skill': typeof JobsLocationsLocationSkillsSkillRoute
  '/employers/companies/$slug/jobs/$jobId/applicants': typeof EmployersCompaniesSlugJobsJobIdApplicantsRoute
  '/employers/companies/$slug/jobs/$jobId/edit': typeof EmployersCompaniesSlugJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/apply': typeof ApplyRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/impressum': typeof ImpressumRoute
  '/indexnow-key.txt': typeof IndexnowKeyDottxtRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRouteWithChildren
  '/password': typeof PasswordRoute
  '/post': typeof PostRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/settings': typeof SettingsRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/.well-known/cavuno.json': typeof DotwellKnownCavunoDotjsonRoute
  '/account_/access': typeof AccountAccessRoute
  '/alerts/confirm': typeof AlertsConfirmRoute
  '/alerts/manage': typeof AlertsManageRoute
  '/auth/confirm-email-change': typeof AuthConfirmEmailChangeRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join': typeof AuthJoinRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/oauth-complete': typeof AuthOauthCompleteRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-email-required': typeof AuthVerifyEmailRequiredRoute
  '/auth/verify-work-email': typeof AuthVerifyWorkEmailRoute
  '/blog/$postSlug': typeof BlogPostSlugRouteWithChildren
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/embed/jobs': typeof EmbedJobsRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
  '/go/$': typeof GoSplatRoute
  '/jobs/$keyword': typeof JobsKeywordRoute
  '/jobs/rss.xml': typeof JobsRssDotxmlRoute
  '/me/alerts': typeof MeAlertsRoute
  '/me/applications': typeof MeApplicationsRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/p/$handle': typeof PHandleRoute
  '/sitemap/$file': typeof SitemapFileRoute
  '/blog/': typeof BlogIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/employers/': typeof EmployersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/salaries/': typeof SalariesIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/auth/employer/sign-up': typeof AuthEmployerSignUpRoute
  '/blog/$postSlug/og': typeof BlogPostSlugOgRoute
  '/blog/author/$authorSlug': typeof BlogAuthorAuthorSlugRoute
  '/blog/og/{$postSlug}.json': typeof BlogOgChar123postSlugChar125DotjsonRoute
  '/blog/tag/$tagSlug': typeof BlogTagTagSlugRoute
  '/companies/markets/$market': typeof CompaniesMarketsMarketRoute
  '/employers/invites/accept': typeof EmployersInvitesAcceptRoute
  '/employers/onboarding/$slug': typeof EmployersOnboardingSlugRoute
  '/jobs/skills/$skill': typeof JobsSkillsSkillRoute
  '/companies/$companySlug/': typeof CompaniesCompanySlugIndexRoute
  '/jobs/locations/': typeof JobsLocationsIndexRoute
  '/salaries/companies/': typeof SalariesCompaniesIndexRoute
  '/salaries/locations/': typeof SalariesLocationsIndexRoute
  '/salaries/skills/': typeof SalariesSkillsIndexRoute
  '/salaries/titles/': typeof SalariesTitlesIndexRoute
  '/companies/$companySlug/jobs/$jobSlug': typeof CompaniesCompanySlugJobsJobSlugRouteWithChildren
  '/companies/$companySlug/salaries/$categorySlug': typeof CompaniesCompanySlugSalariesCategorySlugRoute
  '/employers/companies/$slug/members': typeof EmployersCompaniesSlugMembersRoute
  '/employers/companies/$slug/profile': typeof EmployersCompaniesSlugProfileRoute
  '/jobs/locations/$location/$keyword': typeof JobsLocationsLocationKeywordRoute
  '/salaries/locations/$slug/skills': typeof SalariesLocationsSlugSkillsRoute
  '/salaries/locations/$slug/titles': typeof SalariesLocationsSlugTitlesRoute
  '/salaries/skills/$slug/$locationSlug': typeof SalariesSkillsSlugLocationSlugRoute
  '/salaries/skills/$slug/locations': typeof SalariesSkillsSlugLocationsRoute
  '/salaries/titles/$slug/$locationSlug': typeof SalariesTitlesSlugLocationSlugRoute
  '/salaries/titles/$slug/locations': typeof SalariesTitlesSlugLocationsRoute
  '/companies/$companySlug/jobs/': typeof CompaniesCompanySlugJobsIndexRoute
  '/companies/$companySlug/salaries/': typeof CompaniesCompanySlugSalariesIndexRoute
  '/employers/companies/$slug/': typeof EmployersCompaniesSlugIndexRoute
  '/jobs/locations/$location/': typeof JobsLocationsLocationIndexRoute
  '/salaries/locations/$slug/': typeof SalariesLocationsSlugIndexRoute
  '/salaries/skills/$slug/': typeof SalariesSkillsSlugIndexRoute
  '/salaries/titles/$slug/': typeof SalariesTitlesSlugIndexRoute
  '/companies/$companySlug/jobs/$jobSlug/og': typeof CompaniesCompanySlugJobsJobSlugOgRoute
  '/employers/companies/$slug/jobs/new': typeof EmployersCompaniesSlugJobsNewRoute
  '/jobs/locations/$location/skills/$skill': typeof JobsLocationsLocationSkillsSkillRoute
  '/employers/companies/$slug/jobs/$jobId/applicants': typeof EmployersCompaniesSlugJobsJobIdApplicantsRoute
  '/employers/companies/$slug/jobs/$jobId/edit': typeof EmployersCompaniesSlugJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/ads.txt'
    | '/apply'
    | '/cookie-policy'
    | '/impressum'
    | '/indexnow-key.txt'
    | '/matches'
    | '/messages'
    | '/password'
    | '/post'
    | '/privacy-policy'
    | '/robots.txt'
    | '/saved-jobs'
    | '/settings'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/.well-known/cavuno.json'
    | '/account/access'
    | '/alerts/confirm'
    | '/alerts/manage'
    | '/auth/confirm-email-change'
    | '/auth/forgot-password'
    | '/auth/join'
    | '/auth/magic-link'
    | '/auth/oauth-complete'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/auth/verify-email-required'
    | '/auth/verify-work-email'
    | '/blog/$postSlug'
    | '/blog/rss.xml'
    | '/embed/jobs'
    | '/employers/dashboard'
    | '/go/$'
    | '/jobs/$keyword'
    | '/jobs/rss.xml'
    | '/me/alerts'
    | '/me/applications'
    | '/messages/$conversationId'
    | '/p/$handle'
    | '/sitemap/$file'
    | '/blog/'
    | '/companies/'
    | '/employers/'
    | '/jobs/'
    | '/salaries/'
    | '/talent/'
    | '/auth/employer/sign-up'
    | '/blog/$postSlug/og'
    | '/blog/author/$authorSlug'
    | '/blog/og/{$postSlug}.json'
    | '/blog/tag/$tagSlug'
    | '/companies/markets/$market'
    | '/employers/invites/accept'
    | '/employers/onboarding/$slug'
    | '/jobs/skills/$skill'
    | '/companies/$companySlug/'
    | '/jobs/locations/'
    | '/salaries/companies/'
    | '/salaries/locations/'
    | '/salaries/skills/'
    | '/salaries/titles/'
    | '/companies/$companySlug/jobs/$jobSlug'
    | '/companies/$companySlug/salaries/$categorySlug'
    | '/employers/companies/$slug/members'
    | '/employers/companies/$slug/profile'
    | '/jobs/locations/$location/$keyword'
    | '/salaries/locations/$slug/skills'
    | '/salaries/locations/$slug/titles'
    | '/salaries/skills/$slug/$locationSlug'
    | '/salaries/skills/$slug/locations'
    | '/salaries/titles/$slug/$locationSlug'
    | '/salaries/titles/$slug/locations'
    | '/companies/$companySlug/jobs/'
    | '/companies/$companySlug/salaries/'
    | '/employers/companies/$slug/'
    | '/jobs/locations/$location/'
    | '/salaries/locations/$slug/'
    | '/salaries/skills/$slug/'
    | '/salaries/titles/$slug/'
    | '/companies/$companySlug/jobs/$jobSlug/og'
    | '/employers/companies/$slug/jobs/new'
    | '/jobs/locations/$location/skills/$skill'
    | '/employers/companies/$slug/jobs/$jobId/applicants'
    | '/employers/companies/$slug/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/ads.txt'
    | '/apply'
    | '/cookie-policy'
    | '/impressum'
    | '/indexnow-key.txt'
    | '/matches'
    | '/messages'
    | '/password'
    | '/post'
    | '/privacy-policy'
    | '/robots.txt'
    | '/saved-jobs'
    | '/settings'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/.well-known/cavuno.json'
    | '/account/access'
    | '/alerts/confirm'
    | '/alerts/manage'
    | '/auth/confirm-email-change'
    | '/auth/forgot-password'
    | '/auth/join'
    | '/auth/magic-link'
    | '/auth/oauth-complete'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/auth/verify-email-required'
    | '/auth/verify-work-email'
    | '/blog/$postSlug'
    | '/blog/rss.xml'
    | '/embed/jobs'
    | '/employers/dashboard'
    | '/go/$'
    | '/jobs/$keyword'
    | '/jobs/rss.xml'
    | '/me/alerts'
    | '/me/applications'
    | '/messages/$conversationId'
    | '/p/$handle'
    | '/sitemap/$file'
    | '/blog'
    | '/companies'
    | '/employers'
    | '/jobs'
    | '/salaries'
    | '/talent'
    | '/auth/employer/sign-up'
    | '/blog/$postSlug/og'
    | '/blog/author/$authorSlug'
    | '/blog/og/{$postSlug}.json'
    | '/blog/tag/$tagSlug'
    | '/companies/markets/$market'
    | '/employers/invites/accept'
    | '/employers/onboarding/$slug'
    | '/jobs/skills/$skill'
    | '/companies/$companySlug'
    | '/jobs/locations'
    | '/salaries/companies'
    | '/salaries/locations'
    | '/salaries/skills'
    | '/salaries/titles'
    | '/companies/$companySlug/jobs/$jobSlug'
    | '/companies/$companySlug/salaries/$categorySlug'
    | '/employers/companies/$slug/members'
    | '/employers/companies/$slug/profile'
    | '/jobs/locations/$location/$keyword'
    | '/salaries/locations/$slug/skills'
    | '/salaries/locations/$slug/titles'
    | '/salaries/skills/$slug/$locationSlug'
    | '/salaries/skills/$slug/locations'
    | '/salaries/titles/$slug/$locationSlug'
    | '/salaries/titles/$slug/locations'
    | '/companies/$companySlug/jobs'
    | '/companies/$companySlug/salaries'
    | '/employers/companies/$slug'
    | '/jobs/locations/$location'
    | '/salaries/locations/$slug'
    | '/salaries/skills/$slug'
    | '/salaries/titles/$slug'
    | '/companies/$companySlug/jobs/$jobSlug/og'
    | '/employers/companies/$slug/jobs/new'
    | '/jobs/locations/$location/skills/$skill'
    | '/employers/companies/$slug/jobs/$jobId/applicants'
    | '/employers/companies/$slug/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/ads.txt'
    | '/apply'
    | '/cookie-policy'
    | '/impressum'
    | '/indexnow-key.txt'
    | '/matches'
    | '/messages'
    | '/password'
    | '/post'
    | '/privacy-policy'
    | '/robots.txt'
    | '/saved-jobs'
    | '/settings'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/.well-known/cavuno.json'
    | '/account_/access'
    | '/alerts/confirm'
    | '/alerts/manage'
    | '/auth/confirm-email-change'
    | '/auth/forgot-password'
    | '/auth/join'
    | '/auth/magic-link'
    | '/auth/oauth-complete'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/auth/verify-email-required'
    | '/auth/verify-work-email'
    | '/blog/$postSlug'
    | '/blog/rss.xml'
    | '/embed/jobs'
    | '/employers/dashboard'
    | '/go/$'
    | '/jobs/$keyword'
    | '/jobs/rss.xml'
    | '/me/alerts'
    | '/me/applications'
    | '/messages/$conversationId'
    | '/p/$handle'
    | '/sitemap/$file'
    | '/blog/'
    | '/companies/'
    | '/employers/'
    | '/jobs/'
    | '/salaries/'
    | '/talent/'
    | '/auth/employer/sign-up'
    | '/blog/$postSlug/og'
    | '/blog/author/$authorSlug'
    | '/blog/og/{$postSlug}.json'
    | '/blog/tag/$tagSlug'
    | '/companies/markets/$market'
    | '/employers/invites/accept'
    | '/employers/onboarding/$slug'
    | '/jobs/skills/$skill'
    | '/companies/$companySlug/'
    | '/jobs/locations/'
    | '/salaries/companies/'
    | '/salaries/locations/'
    | '/salaries/skills/'
    | '/salaries/titles/'
    | '/companies/$companySlug/jobs/$jobSlug'
    | '/companies/$companySlug/salaries/$categorySlug'
    | '/employers/companies/$slug/members'
    | '/employers/companies/$slug/profile'
    | '/jobs/locations/$location/$keyword'
    | '/salaries/locations/$slug/skills'
    | '/salaries/locations/$slug/titles'
    | '/salaries/skills/$slug/$locationSlug'
    | '/salaries/skills/$slug/locations'
    | '/salaries/titles/$slug/$locationSlug'
    | '/salaries/titles/$slug/locations'
    | '/companies/$companySlug/jobs/'
    | '/companies/$companySlug/salaries/'
    | '/employers/companies/$slug/'
    | '/jobs/locations/$location/'
    | '/salaries/locations/$slug/'
    | '/salaries/skills/$slug/'
    | '/salaries/titles/$slug/'
    | '/companies/$companySlug/jobs/$jobSlug/og'
    | '/employers/companies/$slug/jobs/new'
    | '/jobs/locations/$location/skills/$skill'
    | '/employers/companies/$slug/jobs/$jobId/applicants'
    | '/employers/companies/$slug/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  ApplyRoute: typeof ApplyRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  ImpressumRoute: typeof ImpressumRoute
  IndexnowKeyDottxtRoute: typeof IndexnowKeyDottxtRoute
  MatchesRoute: typeof MatchesRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PasswordRoute: typeof PasswordRoute
  PostRoute: typeof PostRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SavedJobsRoute: typeof SavedJobsRoute
  SettingsRoute: typeof SettingsRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  DotwellKnownCavunoDotjsonRoute: typeof DotwellKnownCavunoDotjsonRoute
  AccountAccessRoute: typeof AccountAccessRoute
  AlertsConfirmRoute: typeof AlertsConfirmRoute
  AlertsManageRoute: typeof AlertsManageRoute
  AuthConfirmEmailChangeRoute: typeof AuthConfirmEmailChangeRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthJoinRoute: typeof AuthJoinRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthOauthCompleteRoute: typeof AuthOauthCompleteRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyEmailRequiredRoute: typeof AuthVerifyEmailRequiredRoute
  AuthVerifyWorkEmailRoute: typeof AuthVerifyWorkEmailRoute
  BlogPostSlugRoute: typeof BlogPostSlugRouteWithChildren
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  EmbedJobsRoute: typeof EmbedJobsRoute
  EmployersDashboardRoute: typeof EmployersDashboardRoute
  GoSplatRoute: typeof GoSplatRoute
  JobsKeywordRoute: typeof JobsKeywordRoute
  JobsRssDotxmlRoute: typeof JobsRssDotxmlRoute
  MeAlertsRoute: typeof MeAlertsRoute
  MeApplicationsRoute: typeof MeApplicationsRoute
  PHandleRoute: typeof PHandleRoute
  SitemapFileRoute: typeof SitemapFileRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  EmployersIndexRoute: typeof EmployersIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  SalariesIndexRoute: typeof SalariesIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
  AuthEmployerSignUpRoute: typeof AuthEmployerSignUpRoute
  BlogAuthorAuthorSlugRoute: typeof BlogAuthorAuthorSlugRoute
  BlogOgChar123postSlugChar125DotjsonRoute: typeof BlogOgChar123postSlugChar125DotjsonRoute
  BlogTagTagSlugRoute: typeof BlogTagTagSlugRoute
  CompaniesMarketsMarketRoute: typeof CompaniesMarketsMarketRoute
  EmployersInvitesAcceptRoute: typeof EmployersInvitesAcceptRoute
  EmployersOnboardingSlugRoute: typeof EmployersOnboardingSlugRoute
  JobsSkillsSkillRoute: typeof JobsSkillsSkillRoute
  CompaniesCompanySlugIndexRoute: typeof CompaniesCompanySlugIndexRoute
  JobsLocationsIndexRoute: typeof JobsLocationsIndexRoute
  SalariesCompaniesIndexRoute: typeof SalariesCompaniesIndexRoute
  SalariesLocationsIndexRoute: typeof SalariesLocationsIndexRoute
  SalariesSkillsIndexRoute: typeof SalariesSkillsIndexRoute
  SalariesTitlesIndexRoute: typeof SalariesTitlesIndexRoute
  CompaniesCompanySlugJobsJobSlugRoute: typeof CompaniesCompanySlugJobsJobSlugRouteWithChildren
  CompaniesCompanySlugSalariesCategorySlugRoute: typeof CompaniesCompanySlugSalariesCategorySlugRoute
  EmployersCompaniesSlugMembersRoute: typeof EmployersCompaniesSlugMembersRoute
  EmployersCompaniesSlugProfileRoute: typeof EmployersCompaniesSlugProfileRoute
  JobsLocationsLocationKeywordRoute: typeof JobsLocationsLocationKeywordRoute
  SalariesLocationsSlugSkillsRoute: typeof SalariesLocationsSlugSkillsRoute
  SalariesLocationsSlugTitlesRoute: typeof SalariesLocationsSlugTitlesRoute
  SalariesSkillsSlugLocationSlugRoute: typeof SalariesSkillsSlugLocationSlugRoute
  SalariesSkillsSlugLocationsRoute: typeof SalariesSkillsSlugLocationsRoute
  SalariesTitlesSlugLocationSlugRoute: typeof SalariesTitlesSlugLocationSlugRoute
  SalariesTitlesSlugLocationsRoute: typeof SalariesTitlesSlugLocationsRoute
  CompaniesCompanySlugJobsIndexRoute: typeof CompaniesCompanySlugJobsIndexRoute
  CompaniesCompanySlugSalariesIndexRoute: typeof CompaniesCompanySlugSalariesIndexRoute
  EmployersCompaniesSlugIndexRoute: typeof EmployersCompaniesSlugIndexRoute
  JobsLocationsLocationIndexRoute: typeof JobsLocationsLocationIndexRoute
  SalariesLocationsSlugIndexRoute: typeof SalariesLocationsSlugIndexRoute
  SalariesSkillsSlugIndexRoute: typeof SalariesSkillsSlugIndexRoute
  SalariesTitlesSlugIndexRoute: typeof SalariesTitlesSlugIndexRoute
  EmployersCompaniesSlugJobsNewRoute: typeof EmployersCompaniesSlugJobsNewRoute
  JobsLocationsLocationSkillsSkillRoute: typeof JobsLocationsLocationSkillsSkillRoute
  EmployersCompaniesSlugJobsJobIdApplicantsRoute: typeof EmployersCompaniesSlugJobsJobIdApplicantsRoute
  EmployersCompaniesSlugJobsJobIdEditRoute: typeof EmployersCompaniesSlugJobsJobIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexnow-key.txt': {
      id: '/indexnow-key.txt'
      path: '/indexnow-key.txt'
      fullPath: '/indexnow-key.txt'
      preLoaderRoute: typeof IndexnowKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/': {
      id: '/salaries/'
      path: '/salaries'
      fullPath: '/salaries/'
      preLoaderRoute: typeof SalariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/': {
      id: '/employers/'
      path: '/employers'
      fullPath: '/employers/'
      preLoaderRoute: typeof EmployersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$file': {
      id: '/sitemap/$file'
      path: '/sitemap/$file'
      fullPath: '/sitemap/$file'
      preLoaderRoute: typeof SitemapFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/me/applications': {
      id: '/me/applications'
      path: '/me/applications'
      fullPath: '/me/applications'
      preLoaderRoute: typeof MeApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/alerts': {
      id: '/me/alerts'
      path: '/me/alerts'
      fullPath: '/me/alerts'
      preLoaderRoute: typeof MeAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/rss.xml': {
      id: '/jobs/rss.xml'
      path: '/jobs/rss.xml'
      fullPath: '/jobs/rss.xml'
      preLoaderRoute: typeof JobsRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$keyword': {
      id: '/jobs/$keyword'
      path: '/jobs/$keyword'
      fullPath: '/jobs/$keyword'
      preLoaderRoute: typeof JobsKeywordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$': {
      id: '/go/$'
      path: '/go/$'
      fullPath: '/go/$'
      preLoaderRoute: typeof GoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/dashboard': {
      id: '/employers/dashboard'
      path: '/employers/dashboard'
      fullPath: '/employers/dashboard'
      preLoaderRoute: typeof EmployersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/jobs': {
      id: '/embed/jobs'
      path: '/embed/jobs'
      fullPath: '/embed/jobs'
      preLoaderRoute: typeof EmbedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postSlug': {
      id: '/blog/$postSlug'
      path: '/blog/$postSlug'
      fullPath: '/blog/$postSlug'
      preLoaderRoute: typeof BlogPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-work-email': {
      id: '/auth/verify-work-email'
      path: '/auth/verify-work-email'
      fullPath: '/auth/verify-work-email'
      preLoaderRoute: typeof AuthVerifyWorkEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email-required': {
      id: '/auth/verify-email-required'
      path: '/auth/verify-email-required'
      fullPath: '/auth/verify-email-required'
      preLoaderRoute: typeof AuthVerifyEmailRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/oauth-complete': {
      id: '/auth/oauth-complete'
      path: '/auth/oauth-complete'
      fullPath: '/auth/oauth-complete'
      preLoaderRoute: typeof AuthOauthCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/auth/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/join': {
      id: '/auth/join'
      path: '/auth/join'
      fullPath: '/auth/join'
      preLoaderRoute: typeof AuthJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm-email-change': {
      id: '/auth/confirm-email-change'
      path: '/auth/confirm-email-change'
      fullPath: '/auth/confirm-email-change'
      preLoaderRoute: typeof AuthConfirmEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/manage': {
      id: '/alerts/manage'
      path: '/alerts/manage'
      fullPath: '/alerts/manage'
      preLoaderRoute: typeof AlertsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/confirm': {
      id: '/alerts/confirm'
      path: '/alerts/confirm'
      fullPath: '/alerts/confirm'
      preLoaderRoute: typeof AlertsConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/access': {
      id: '/account_/access'
      path: '/account/access'
      fullPath: '/account/access'
      preLoaderRoute: typeof AccountAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/cavuno.json': {
      id: '/.well-known/cavuno.json'
      path: '/.well-known/cavuno.json'
      fullPath: '/.well-known/cavuno.json'
      preLoaderRoute: typeof DotwellKnownCavunoDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/titles/': {
      id: '/salaries/titles/'
      path: '/salaries/titles'
      fullPath: '/salaries/titles/'
      preLoaderRoute: typeof SalariesTitlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/skills/': {
      id: '/salaries/skills/'
      path: '/salaries/skills'
      fullPath: '/salaries/skills/'
      preLoaderRoute: typeof SalariesSkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/locations/': {
      id: '/salaries/locations/'
      path: '/salaries/locations'
      fullPath: '/salaries/locations/'
      preLoaderRoute: typeof SalariesLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/companies/': {
      id: '/salaries/companies/'
      path: '/salaries/companies'
      fullPath: '/salaries/companies/'
      preLoaderRoute: typeof SalariesCompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/locations/': {
      id: '/jobs/locations/'
      path: '/jobs/locations'
      fullPath: '/jobs/locations/'
      preLoaderRoute: typeof JobsLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companySlug/': {
      id: '/companies/$companySlug/'
      path: '/companies/$companySlug'
      fullPath: '/companies/$companySlug/'
      preLoaderRoute: typeof CompaniesCompanySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/skills/$skill': {
      id: '/jobs/skills/$skill'
      path: '/jobs/skills/$skill'
      fullPath: '/jobs/skills/$skill'
      preLoaderRoute: typeof JobsSkillsSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/onboarding/$slug': {
      id: '/employers/onboarding/$slug'
      path: '/employers/onboarding/$slug'
      fullPath: '/employers/onboarding/$slug'
      preLoaderRoute: typeof EmployersOnboardingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/invites/accept': {
      id: '/employers/invites/accept'
      path: '/employers/invites/accept'
      fullPath: '/employers/invites/accept'
      preLoaderRoute: typeof EmployersInvitesAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/markets/$market': {
      id: '/companies/markets/$market'
      path: '/companies/markets/$market'
      fullPath: '/companies/markets/$market'
      preLoaderRoute: typeof CompaniesMarketsMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$tagSlug': {
      id: '/blog/tag/$tagSlug'
      path: '/blog/tag/$tagSlug'
      fullPath: '/blog/tag/$tagSlug'
      preLoaderRoute: typeof BlogTagTagSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/og/{$postSlug}.json': {
      id: '/blog/og/{$postSlug}.json'
      path: '/blog/og/{$postSlug}.json'
      fullPath: '/blog/og/{$postSlug}.json'
      preLoaderRoute: typeof BlogOgChar123postSlugChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/author/$authorSlug': {
      id: '/blog/author/$authorSlug'
      path: '/blog/author/$authorSlug'
      fullPath: '/blog/author/$authorSlug'
      preLoaderRoute: typeof BlogAuthorAuthorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$postSlug/og': {
      id: '/blog/$postSlug/og'
      path: '/og'
      fullPath: '/blog/$postSlug/og'
      preLoaderRoute: typeof BlogPostSlugOgRouteImport
      parentRoute: typeof BlogPostSlugRoute
    }
    '/auth/employer/sign-up': {
      id: '/auth/employer/sign-up'
      path: '/auth/employer/sign-up'
      fullPath: '/auth/employer/sign-up'
      preLoaderRoute: typeof AuthEmployerSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/titles/$slug/': {
      id: '/salaries/titles/$slug/'
      path: '/salaries/titles/$slug'
      fullPath: '/salaries/titles/$slug/'
      preLoaderRoute: typeof SalariesTitlesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/skills/$slug/': {
      id: '/salaries/skills/$slug/'
      path: '/salaries/skills/$slug'
      fullPath: '/salaries/skills/$slug/'
      preLoaderRoute: typeof SalariesSkillsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/locations/$slug/': {
      id: '/salaries/locations/$slug/'
      path: '/salaries/locations/$slug'
      fullPath: '/salaries/locations/$slug/'
      preLoaderRoute: typeof SalariesLocationsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/locations/$location/': {
      id: '/jobs/locations/$location/'
      path: '/jobs/locations/$location'
      fullPath: '/jobs/locations/$location/'
      preLoaderRoute: typeof JobsLocationsLocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/companies/$slug/': {
      id: '/employers/companies/$slug/'
      path: '/employers/companies/$slug'
      fullPath: '/employers/companies/$slug/'
      preLoaderRoute: typeof EmployersCompaniesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companySlug/salaries/': {
      id: '/companies/$companySlug/salaries/'
      path: '/companies/$companySlug/salaries'
      fullPath: '/companies/$companySlug/salaries/'
      preLoaderRoute: typeof CompaniesCompanySlugSalariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companySlug/jobs/': {
      id: '/companies/$companySlug/jobs/'
      path: '/companies/$companySlug/jobs'
      fullPath: '/companies/$companySlug/jobs/'
      preLoaderRoute: typeof CompaniesCompanySlugJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/titles/$slug/locations': {
      id: '/salaries/titles/$slug/locations'
      path: '/salaries/titles/$slug/locations'
      fullPath: '/salaries/titles/$slug/locations'
      preLoaderRoute: typeof SalariesTitlesSlugLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/titles/$slug/$locationSlug': {
      id: '/salaries/titles/$slug/$locationSlug'
      path: '/salaries/titles/$slug/$locationSlug'
      fullPath: '/salaries/titles/$slug/$locationSlug'
      preLoaderRoute: typeof SalariesTitlesSlugLocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/skills/$slug/locations': {
      id: '/salaries/skills/$slug/locations'
      path: '/salaries/skills/$slug/locations'
      fullPath: '/salaries/skills/$slug/locations'
      preLoaderRoute: typeof SalariesSkillsSlugLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/skills/$slug/$locationSlug': {
      id: '/salaries/skills/$slug/$locationSlug'
      path: '/salaries/skills/$slug/$locationSlug'
      fullPath: '/salaries/skills/$slug/$locationSlug'
      preLoaderRoute: typeof SalariesSkillsSlugLocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/locations/$slug/titles': {
      id: '/salaries/locations/$slug/titles'
      path: '/salaries/locations/$slug/titles'
      fullPath: '/salaries/locations/$slug/titles'
      preLoaderRoute: typeof SalariesLocationsSlugTitlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaries/locations/$slug/skills': {
      id: '/salaries/locations/$slug/skills'
      path: '/salaries/locations/$slug/skills'
      fullPath: '/salaries/locations/$slug/skills'
      preLoaderRoute: typeof SalariesLocationsSlugSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/locations/$location/$keyword': {
      id: '/jobs/locations/$location/$keyword'
      path: '/jobs/locations/$location/$keyword'
      fullPath: '/jobs/locations/$location/$keyword'
      preLoaderRoute: typeof JobsLocationsLocationKeywordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/companies/$slug/profile': {
      id: '/employers/companies/$slug/profile'
      path: '/employers/companies/$slug/profile'
      fullPath: '/employers/companies/$slug/profile'
      preLoaderRoute: typeof EmployersCompaniesSlugProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/companies/$slug/members': {
      id: '/employers/companies/$slug/members'
      path: '/employers/companies/$slug/members'
      fullPath: '/employers/companies/$slug/members'
      preLoaderRoute: typeof EmployersCompaniesSlugMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companySlug/salaries/$categorySlug': {
      id: '/companies/$companySlug/salaries/$categorySlug'
      path: '/companies/$companySlug/salaries/$categorySlug'
      fullPath: '/companies/$companySlug/salaries/$categorySlug'
      preLoaderRoute: typeof CompaniesCompanySlugSalariesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companySlug/jobs/$jobSlug': {
      id: '/companies/$companySlug/jobs/$jobSlug'
      path: '/companies/$companySlug/jobs/$jobSlug'
      fullPath: '/companies/$companySlug/jobs/$jobSlug'
      preLoaderRoute: typeof CompaniesCompanySlugJobsJobSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/locations/$location/skills/$skill': {
      id: '/jobs/locations/$location/skills/$skill'
      path: '/jobs/locations/$location/skills/$skill'
      fullPath: '/jobs/locations/$location/skills/$skill'
      preLoaderRoute: typeof JobsLocationsLocationSkillsSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/companies/$slug/jobs/new': {
      id: '/employers/companies/$slug/jobs/new'
      path: '/employers/companies/$slug/jobs/new'
      fullPath: '/employers/companies/$slug/jobs/new'
      preLoaderRoute: typeof EmployersCompaniesSlugJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companySlug/jobs/$jobSlug/og': {
      id: '/companies/$companySlug/jobs/$jobSlug/og'
      path: '/og'
      fullPath: '/companies/$companySlug/jobs/$jobSlug/og'
      preLoaderRoute: typeof CompaniesCompanySlugJobsJobSlugOgRouteImport
      parentRoute: typeof CompaniesCompanySlugJobsJobSlugRoute
    }
    '/employers/companies/$slug/jobs/$jobId/edit': {
      id: '/employers/companies/$slug/jobs/$jobId/edit'
      path: '/employers/companies/$slug/jobs/$jobId/edit'
      fullPath: '/employers/companies/$slug/jobs/$jobId/edit'
      preLoaderRoute: typeof EmployersCompaniesSlugJobsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/companies/$slug/jobs/$jobId/applicants': {
      id: '/employers/companies/$slug/jobs/$jobId/applicants'
      path: '/employers/companies/$slug/jobs/$jobId/applicants'
      fullPath: '/employers/companies/$slug/jobs/$jobId/applicants'
      preLoaderRoute: typeof EmployersCompaniesSlugJobsJobIdApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesConversationIdRoute: MessagesConversationIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface BlogPostSlugRouteChildren {
  BlogPostSlugOgRoute: typeof BlogPostSlugOgRoute
}

const BlogPostSlugRouteChildren: BlogPostSlugRouteChildren = {
  BlogPostSlugOgRoute: BlogPostSlugOgRoute,
}

const BlogPostSlugRouteWithChildren = BlogPostSlugRoute._addFileChildren(
  BlogPostSlugRouteChildren,
)

interface CompaniesCompanySlugJobsJobSlugRouteChildren {
  CompaniesCompanySlugJobsJobSlugOgRoute: typeof CompaniesCompanySlugJobsJobSlugOgRoute
}

const CompaniesCompanySlugJobsJobSlugRouteChildren: CompaniesCompanySlugJobsJobSlugRouteChildren =
  {
    CompaniesCompanySlugJobsJobSlugOgRoute:
      CompaniesCompanySlugJobsJobSlugOgRoute,
  }

const CompaniesCompanySlugJobsJobSlugRouteWithChildren =
  CompaniesCompanySlugJobsJobSlugRoute._addFileChildren(
    CompaniesCompanySlugJobsJobSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  ApplyRoute: ApplyRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  ImpressumRoute: ImpressumRoute,
  IndexnowKeyDottxtRoute: IndexnowKeyDottxtRoute,
  MatchesRoute: MatchesRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PasswordRoute: PasswordRoute,
  PostRoute: PostRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SavedJobsRoute: SavedJobsRoute,
  SettingsRoute: SettingsRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  DotwellKnownCavunoDotjsonRoute: DotwellKnownCavunoDotjsonRoute,
  AccountAccessRoute: AccountAccessRoute,
  AlertsConfirmRoute: AlertsConfirmRoute,
  AlertsManageRoute: AlertsManageRoute,
  AuthConfirmEmailChangeRoute: AuthConfirmEmailChangeRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthJoinRoute: AuthJoinRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthOauthCompleteRoute: AuthOauthCompleteRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyEmailRequiredRoute: AuthVerifyEmailRequiredRoute,
  AuthVerifyWorkEmailRoute: AuthVerifyWorkEmailRoute,
  BlogPostSlugRoute: BlogPostSlugRouteWithChildren,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  EmbedJobsRoute: EmbedJobsRoute,
  EmployersDashboardRoute: EmployersDashboardRoute,
  GoSplatRoute: GoSplatRoute,
  JobsKeywordRoute: JobsKeywordRoute,
  JobsRssDotxmlRoute: JobsRssDotxmlRoute,
  MeAlertsRoute: MeAlertsRoute,
  MeApplicationsRoute: MeApplicationsRoute,
  PHandleRoute: PHandleRoute,
  SitemapFileRoute: SitemapFileRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  EmployersIndexRoute: EmployersIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  SalariesIndexRoute: SalariesIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
  AuthEmployerSignUpRoute: AuthEmployerSignUpRoute,
  BlogAuthorAuthorSlugRoute: BlogAuthorAuthorSlugRoute,
  BlogOgChar123postSlugChar125DotjsonRoute:
    BlogOgChar123postSlugChar125DotjsonRoute,
  BlogTagTagSlugRoute: BlogTagTagSlugRoute,
  CompaniesMarketsMarketRoute: CompaniesMarketsMarketRoute,
  EmployersInvitesAcceptRoute: EmployersInvitesAcceptRoute,
  EmployersOnboardingSlugRoute: EmployersOnboardingSlugRoute,
  JobsSkillsSkillRoute: JobsSkillsSkillRoute,
  CompaniesCompanySlugIndexRoute: CompaniesCompanySlugIndexRoute,
  JobsLocationsIndexRoute: JobsLocationsIndexRoute,
  SalariesCompaniesIndexRoute: SalariesCompaniesIndexRoute,
  SalariesLocationsIndexRoute: SalariesLocationsIndexRoute,
  SalariesSkillsIndexRoute: SalariesSkillsIndexRoute,
  SalariesTitlesIndexRoute: SalariesTitlesIndexRoute,
  CompaniesCompanySlugJobsJobSlugRoute:
    CompaniesCompanySlugJobsJobSlugRouteWithChildren,
  CompaniesCompanySlugSalariesCategorySlugRoute:
    CompaniesCompanySlugSalariesCategorySlugRoute,
  EmployersCompaniesSlugMembersRoute: EmployersCompaniesSlugMembersRoute,
  EmployersCompaniesSlugProfileRoute: EmployersCompaniesSlugProfileRoute,
  JobsLocationsLocationKeywordRoute: JobsLocationsLocationKeywordRoute,
  SalariesLocationsSlugSkillsRoute: SalariesLocationsSlugSkillsRoute,
  SalariesLocationsSlugTitlesRoute: SalariesLocationsSlugTitlesRoute,
  SalariesSkillsSlugLocationSlugRoute: SalariesSkillsSlugLocationSlugRoute,
  SalariesSkillsSlugLocationsRoute: SalariesSkillsSlugLocationsRoute,
  SalariesTitlesSlugLocationSlugRoute: SalariesTitlesSlugLocationSlugRoute,
  SalariesTitlesSlugLocationsRoute: SalariesTitlesSlugLocationsRoute,
  CompaniesCompanySlugJobsIndexRoute: CompaniesCompanySlugJobsIndexRoute,
  CompaniesCompanySlugSalariesIndexRoute:
    CompaniesCompanySlugSalariesIndexRoute,
  EmployersCompaniesSlugIndexRoute: EmployersCompaniesSlugIndexRoute,
  JobsLocationsLocationIndexRoute: JobsLocationsLocationIndexRoute,
  SalariesLocationsSlugIndexRoute: SalariesLocationsSlugIndexRoute,
  SalariesSkillsSlugIndexRoute: SalariesSkillsSlugIndexRoute,
  SalariesTitlesSlugIndexRoute: SalariesTitlesSlugIndexRoute,
  EmployersCompaniesSlugJobsNewRoute: EmployersCompaniesSlugJobsNewRoute,
  JobsLocationsLocationSkillsSkillRoute: JobsLocationsLocationSkillsSkillRoute,
  EmployersCompaniesSlugJobsJobIdApplicantsRoute:
    EmployersCompaniesSlugJobsJobIdApplicantsRoute,
  EmployersCompaniesSlugJobsJobIdEditRoute:
    EmployersCompaniesSlugJobsJobIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
